name: Deploy ADF

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      - name: Deploy ADF resources
        uses: Azure/arm-deploy@v2
        with:
          subscriptionId: "4f0bc2fe-ba53-4d30-98ca-24d15413f123"
          resourceGroupName: "stg-resource-group"
          template: "./infrastructure/azure/adf/deployment.json"
