name: Deploy ADF

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      - name: Deploy ADF resources
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: "stg-resource-group"
          dataFactoryName: "olympicsdata-adf-02012025"
          armTemplateFile: "./infrastructure/azure/adf/deployment.json"
